#!/bin/sh
### Checks status of virtual machines and reports critical if there are any
### Author : Nitesh Mestry
### Date : 19|07|2016

### Removing old log files
rm /tmp/vdomstate /tmp/vdomcritical /tmp/vdomok
for VDOM1 in ` virsh list |  sed '1d;2d;$d'| awk '{print $2}'`;
	do
	#echo "##dom list status" $VDOM1
	echo "$VDOM1 ` virsh domstate $VDOM1`" > /tmp/vdomstate
	VDOM_STATE=`cat /tmp/vdomstate | awk '{print $2}'`
	#echo $VDOM_STATE
	VDOM=`cat /tmp/vdomstate | awk '{print $1}'`
	#echo $VDOM
		if [ "$VDOM_STATE" != "running" ]; then
		   echo "Critical : Host $VDOM is $VDOM_STATE" >> /tmp/vdomcritical
		else
		   echo "OK : Host $VDOM is $VDOM_STATE" >> /tmp/vdomok
		fi
	done
	if [ -f /tmp/vdomcritical ]; then
	   echo `cat /tmp/vdomcritical`
	   exit 2
	else
	   echo `cat /tmp/vdomok`
	   exit 0
	fi
